services:
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      target: dependencies
    command: npm run start:dev
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app
      # ignore our local node_modules in the container
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    # healthcheck: 
    # todo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    command: npm run dev
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    # healthcheck:
    # todo

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.db
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    # healthcheck:
    # todo

networks:
  app-network:
    driver: bridge

volumes:
# store data in docker volume for persistence
  db: 
