services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules # ignore our local node_modules in the container
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.db
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data

restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db: # store data in docker volume for persistence
